### ISSUE TITLE
Whenever I migrate i'm getting an SSL error on my localhost.

### ISSUE THREAD

**Issue by bdlowery** [hrsetyono/wp-sync-db#1]
When I migrate from live to local the plugin is changing everything to has https:// at the beginning of it. localhost doesn't allow https.

under wp_options the siteurl and homeurl are being changed to have https:// by default in their value.

I was able to fix this by doing a find and replace on my database, and I could only remove the error once the site_url and home values were changed from https://localhost:888 --> http://localhost:888

Is there something I can edit in the code to make sure it never uses https:// when replacing the urls inside of the database?

**Comment by hrsetyono** [comment]
Hi @bdlowery, After you paste in the sync code, you can change what to search & replace.

The default is keeping the https / http, but you can simply change that.

**Comment by bdlowery** [comment]
Hey! Thanks for the response.

I tried doing a complete search of the code to find anything with 'https' and changed it to be 'http', but that didn't work. 

Namely in this file (if you ctrl + f for https) -- https://github.com/hrsetyono/wp-sync-db/blob/master/class/wpsdb.php

I must be missing something.

**Comment by EmSixTeen** [comment]
It's part of the options when you're syncing the database, not something you change in the actual plugin's code.

**Comment by hrsetyono** [comment]
@bdlowery It's in this setting below as said by @EmSixTeen , thanks for helping to answer

![image](https://user-images.githubusercontent.com/3876541/182981184-d9090ebe-7bca-4e73-bd1c-7683c4ecddb5.png)

**Comment by bdlowery** [comment]
Does the http:// part of the text manually pop up for you? All I see is `//localhost:8888`. Are you saying to manually add `http://localhost:8888` to the replace box?

Thanks!

**Comment by hrsetyono** [comment]
@bdlowery Yes, it's a text field, so you can type it manually
